apiVersion: apps/v1          # Use the Deployment API version
kind: Deployment             # Create a Kubernetes Deployment

metadata:
  name: ci-cd-demo           # Name of the Deployment

spec:
  replicas: 2                # Maintain 2 identical Pods at all times

  selector:
    matchLabels:
      app: ci-cd-demo        # Manage Pods having this label

  template:
    metadata:
      labels:
        app: ci-cd-demo      # Label assigned to newly created Pods

    spec:
      containers:
      - name: ci-cd-container               # Name of the container inside the Pod
        image: ashishkadam720/cicd-demo:latest   # Docker image to pull from Docker Hub